// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.musala.muffinshop.domain;

import com.musala.muffinshop.domain.Icing;
import com.musala.muffinshop.domain.IcingDataOnDemand;
import com.musala.muffinshop.domain.IcingIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IcingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IcingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IcingIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: IcingIntegrationTest: @Transactional;
    
    @Autowired
    IcingDataOnDemand IcingIntegrationTest.dod;
    
    @Test
    public void IcingIntegrationTest.testCountIcings() {
        Assert.assertNotNull("Data on demand for 'Icing' failed to initialize correctly", dod.getRandomIcing());
        long count = Icing.countIcings();
        Assert.assertTrue("Counter for 'Icing' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IcingIntegrationTest.testFindIcing() {
        Icing obj = dod.getRandomIcing();
        Assert.assertNotNull("Data on demand for 'Icing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Icing' failed to provide an identifier", id);
        obj = Icing.findIcing(id);
        Assert.assertNotNull("Find method for 'Icing' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Icing' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IcingIntegrationTest.testFindAllIcings() {
        Assert.assertNotNull("Data on demand for 'Icing' failed to initialize correctly", dod.getRandomIcing());
        long count = Icing.countIcings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Icing', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Icing> result = Icing.findAllIcings();
        Assert.assertNotNull("Find all method for 'Icing' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Icing' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IcingIntegrationTest.testFindIcingEntries() {
        Assert.assertNotNull("Data on demand for 'Icing' failed to initialize correctly", dod.getRandomIcing());
        long count = Icing.countIcings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Icing> result = Icing.findIcingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Icing' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Icing' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IcingIntegrationTest.testFlush() {
        Icing obj = dod.getRandomIcing();
        Assert.assertNotNull("Data on demand for 'Icing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Icing' failed to provide an identifier", id);
        obj = Icing.findIcing(id);
        Assert.assertNotNull("Find method for 'Icing' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyIcing(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Icing' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IcingIntegrationTest.testMergeUpdate() {
        Icing obj = dod.getRandomIcing();
        Assert.assertNotNull("Data on demand for 'Icing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Icing' failed to provide an identifier", id);
        obj = Icing.findIcing(id);
        boolean modified =  dod.modifyIcing(obj);
        Integer currentVersion = obj.getVersion();
        Icing merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Icing' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IcingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Icing' failed to initialize correctly", dod.getRandomIcing());
        Icing obj = dod.getNewTransientIcing(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Icing' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Icing' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Icing' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IcingIntegrationTest.testRemove() {
        Icing obj = dod.getRandomIcing();
        Assert.assertNotNull("Data on demand for 'Icing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Icing' failed to provide an identifier", id);
        obj = Icing.findIcing(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Icing' with identifier '" + id + "'", Icing.findIcing(id));
    }
    
}
