// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.musala.muffinshop.domain;

import com.musala.muffinshop.domain.BaseDataOnDemand;
import com.musala.muffinshop.domain.Muffin;
import com.musala.muffinshop.domain.MuffinDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MuffinDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MuffinDataOnDemand: @Component;
    
    private Random MuffinDataOnDemand.rnd = new SecureRandom();
    
    private List<Muffin> MuffinDataOnDemand.data;
    
    @Autowired
    BaseDataOnDemand MuffinDataOnDemand.baseDataOnDemand;
    
    public Muffin MuffinDataOnDemand.getNewTransientMuffin(int index) {
        Muffin obj = new Muffin();
        setName(obj, index);
        setPrice(obj, index);
        return obj;
    }
    
    public void MuffinDataOnDemand.setName(Muffin obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void MuffinDataOnDemand.setPrice(Muffin obj, int index) {
        Float price = new Integer(index).floatValue();
        obj.setPrice(price);
    }
    
    public Muffin MuffinDataOnDemand.getSpecificMuffin(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Muffin obj = data.get(index);
        Long id = obj.getId();
        return Muffin.findMuffin(id);
    }
    
    public Muffin MuffinDataOnDemand.getRandomMuffin() {
        init();
        Muffin obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Muffin.findMuffin(id);
    }
    
    public boolean MuffinDataOnDemand.modifyMuffin(Muffin obj) {
        return false;
    }
    
    public void MuffinDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Muffin.findMuffinEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Muffin' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Muffin>();
        for (int i = 0; i < 10; i++) {
            Muffin obj = getNewTransientMuffin(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
