// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.musala.muffinshop.domain;

import com.musala.muffinshop.domain.Muffin;
import com.musala.muffinshop.domain.MuffinDataOnDemand;
import com.musala.muffinshop.domain.MuffinIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MuffinIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MuffinIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MuffinIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MuffinIntegrationTest: @Transactional;
    
    @Autowired
    MuffinDataOnDemand MuffinIntegrationTest.dod;
    
    @Test
    public void MuffinIntegrationTest.testCountMuffins() {
        Assert.assertNotNull("Data on demand for 'Muffin' failed to initialize correctly", dod.getRandomMuffin());
        long count = Muffin.countMuffins();
        Assert.assertTrue("Counter for 'Muffin' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MuffinIntegrationTest.testFindMuffin() {
        Muffin obj = dod.getRandomMuffin();
        Assert.assertNotNull("Data on demand for 'Muffin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Muffin' failed to provide an identifier", id);
        obj = Muffin.findMuffin(id);
        Assert.assertNotNull("Find method for 'Muffin' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Muffin' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MuffinIntegrationTest.testFindAllMuffins() {
        Assert.assertNotNull("Data on demand for 'Muffin' failed to initialize correctly", dod.getRandomMuffin());
        long count = Muffin.countMuffins();
        Assert.assertTrue("Too expensive to perform a find all test for 'Muffin', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Muffin> result = Muffin.findAllMuffins();
        Assert.assertNotNull("Find all method for 'Muffin' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Muffin' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MuffinIntegrationTest.testFindMuffinEntries() {
        Assert.assertNotNull("Data on demand for 'Muffin' failed to initialize correctly", dod.getRandomMuffin());
        long count = Muffin.countMuffins();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Muffin> result = Muffin.findMuffinEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Muffin' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Muffin' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MuffinIntegrationTest.testFlush() {
        Muffin obj = dod.getRandomMuffin();
        Assert.assertNotNull("Data on demand for 'Muffin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Muffin' failed to provide an identifier", id);
        obj = Muffin.findMuffin(id);
        Assert.assertNotNull("Find method for 'Muffin' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMuffin(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Muffin' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MuffinIntegrationTest.testMergeUpdate() {
        Muffin obj = dod.getRandomMuffin();
        Assert.assertNotNull("Data on demand for 'Muffin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Muffin' failed to provide an identifier", id);
        obj = Muffin.findMuffin(id);
        boolean modified =  dod.modifyMuffin(obj);
        Integer currentVersion = obj.getVersion();
        Muffin merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Muffin' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MuffinIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Muffin' failed to initialize correctly", dod.getRandomMuffin());
        Muffin obj = dod.getNewTransientMuffin(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Muffin' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Muffin' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Muffin' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MuffinIntegrationTest.testRemove() {
        Muffin obj = dod.getRandomMuffin();
        Assert.assertNotNull("Data on demand for 'Muffin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Muffin' failed to provide an identifier", id);
        obj = Muffin.findMuffin(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Muffin' with identifier '" + id + "'", Muffin.findMuffin(id));
    }
    
}
