// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.musala.muffinshop.domain;

import com.musala.muffinshop.domain.Base;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Base_Roo_Configurable {
    
    declare @type: Base: @Configurable;
    
}
