// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.musala.muffinshop.domain;

import com.musala.muffinshop.domain.Icing;

privileged aspect Icing_Roo_JavaBean {
    
    public String Icing.getName() {
        return this.name;
    }
    
    public void Icing.setName(String name) {
        this.name = name;
    }
    
}
